name: app_chat
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  amazon_cognito_identity_dart_2: ^3.8.1
  flutter_secure_storage: ^10.0.0-beta.4
  provider: ^6.1.5
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  equatable: ^2.0.7
  form_validator: ^2.1.1
  retrofit: ^4.4.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - .env

dependency_overrides:
  async: ^2.13.0
  flutter_secure_storage_macos: ^4.0.0
  material_color_utilities: ^0.12.0
  vector_math: ^2.1.5
  fake_async: ^1.3.3
  leak_tracker: ^11.0.1
  leak_tracker_flutter_testing: ^3.0.10
  leak_tracker_testing: ^3.0.2
  lints: ^6.0.0
  test_api: ^0.7.5
  vm_service: ^15.0.0
